language:
  java

jdk:
  - openjdk8

script:
  - ./gradlew test
  - docker build -t auto-assemble-tests .
  - docker run -d -p 8080:8080 --name auto-assemble-tests_container auto-assemble-tests && sleep 10
  - curl http://127.0.0.1:8080/v1/info
  - docker stop auto-assemble-tests_container
  - docker rm auto-assemble-tests_container
  - docker rmi auto-assemble-tests

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
